In [1]:
from sklearn.datasets import make_classification

In [2]:
X, _ = make_classification(
    n_samples=500,
    n_features=4,
    n_informative=3,
    n_redundant=0,
    n_classes=3,
    random_state=42
)

In [6]:
X[:5]

array([[ 1.39568381, -0.07977213,  2.18861479,  2.02755692],
       [ 0.04360245, -0.33627763, -1.25319985, -1.75734792],
       [ 1.17312464,  0.45623143, -0.91965727,  0.46931124],
       [ 1.08004807, -2.42315325,  1.22719022, -2.51059987],
       [-0.07964139,  1.37900766,  1.6269294 , -0.5177027 ]])

In [7]:
import numpy as np

In [8]:
np.random.seed(42)
labels = np.random.choice(['storke', 'drug_overdose', 'seizure'], size=500)

In [9]:
labels[:10]

array(['seizure', 'storke', 'seizure', 'seizure', 'storke', 'storke',
       'seizure', 'drug_overdose', 'seizure', 'seizure'], dtype='<U13')

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, labels, test_size=0.1, random_state=42)

In [13]:
len(X_test)

50

In [15]:
from sklearn.linear_model import LogisticRegression

In [16]:
model = LogisticRegression(multi_class='multinomial')

In [17]:
model.fit(X_train, y_train)

LogisticRegression(multi_class='multinomial')

In [18]:
model.intercept_

array([ 0.03703316, -0.05077507,  0.01374191])

In [19]:
model.coef_

array([[ 0.01492597,  0.05051006, -0.01323822,  0.09752163],
       [-0.09368829, -0.00985271, -0.01353118, -0.07134933],
       [ 0.07876232, -0.04065735,  0.0267694 , -0.0261723 ]])

In [20]:
prediction_probabilities = model.predict_proba(X_test)

In [21]:
prediction_probabilities

array([[0.25206705, 0.36061781, 0.38731513],
       [0.28043749, 0.35256677, 0.36699574],
       [0.26318459, 0.36913225, 0.36768316],
       [0.23563819, 0.37025306, 0.39410875],
       [0.38836169, 0.26362486, 0.34801345],
       [0.31562836, 0.39171007, 0.29266157],
       [0.39705989, 0.28140725, 0.32153285],
       [0.28720967, 0.33893964, 0.37385068],
       [0.28688053, 0.32423984, 0.38887963],
       [0.3219374 , 0.36101177, 0.31705083],
       [0.29886654, 0.37073503, 0.33039843],
       [0.32338507, 0.37979012, 0.29682482],
       [0.35563234, 0.29320032, 0.35116734],
       [0.25980468, 0.38562332, 0.35457199],
       [0.33961537, 0.31171999, 0.34866464],
       [0.34801607, 0.30383704, 0.34814689],
       [0.26512854, 0.34196237, 0.39290909],
       [0.36796158, 0.28813451, 0.3439039 ],
       [0.3132388 , 0.3978638 , 0.2888974 ],
       [0.35035815, 0.33747183, 0.31217002],
       [0.34346305, 0.29192679, 0.36461016],
       [0.27449388, 0.39720103, 0.32830509],
       [0.

In [22]:
model.classes_

array(['drug_overdose', 'seizure', 'storke'], dtype='<U13')

In [23]:
predictions = model.predict(X_test)

In [24]:
predictions[:5]

array(['storke', 'storke', 'seizure', 'storke', 'drug_overdose'],
      dtype='<U13')

In [25]:
import pandas as pd

In [26]:
pd.concat([
    pd.DataFrame(data=X_test, columns=['A', 'B', 'C', 'D']),
    pd.DataFrame(data=prediction_probabilities, columns=model.classes_),
    pd.DataFrame(data=predictions, columns=['Prediction']),
    pd.DataFrame(data=y_test, columns=['Labels'])
], axis=1)

A         B         C         D  drug_overdose   seizure    storke  \
0   0.061680 -1.728085  0.900421 -2.064197       0.252067  0.360618  0.387315   
1  -0.258905 -0.406071  1.948586 -1.567089       0.280437  0.352567  0.366996   
2   0.350630  0.141539  0.047515 -2.799467       0.263185  0.369132  0.367683   
3   0.075434 -1.757922  1.216953 -2.618177       0.235638  0.370253  0.394109   
4   1.392465  0.611147 -0.942989  0.661723       0.388362  0.263625  0.348013   
5  -0.939903  1.317129 -1.942664 -1.661708       0.315628  0.391710  0.292662   
6   0.260322  0.552427 -0.279050  1.154355       0.397060  0.281407  0.321533   
7   0.950308 -0.341814 -1.268070 -1.987496       0.287210  0.338940  0.373851   
8   1.085982 -0.887330 -0.593605 -1.625166       0.286881  0.324240  0.388880   
9  -0.535963 -0.501855 -2.161461 -0.670464       0.321937  0.361012  0.317051   
10 -0.246062 -0.503942 -2.161578 -1.453893       0.298867  0.370735  0.330398   
11 -1.979300 -0.773851  0.074405  0.077497       0.323385  0.379790  0.296825   
12  0.807123  0.361727 -0.273845 -0.024791       0.355632  0.293200  0.351167   
13 -0.734592 -1.297113  0.624281 -1.923585       0.259805  0.385623  0.354572   
14  0.659246 -0.548294 -1.795670 -0.237345       0.339615  0.311720  0.348665   
15  0.377100 -0.185375 -0.099179  0.107829       0.348016  0.303837  0.348147   
16  0.176442 -1.791281  1.405334 -1.502587       0.265129  0.341962  0.392909   
17  0.747910  0.763165 -0.023054  0.174389       0.367962  0.288135  0.343904   
18 -2.121855  0.292258  0.519501 -0.676742       0.313239  0.397864  0.288897   
19 -0.903702  1.217117  1.435705 -0.154370       0.350358  0.337472  0.312170   
20  1.238946  0.877508  0.033591 -0.667833       0.343463  0.291927  0.364610   
21 -1.006543  0.127365  0.438574 -2.107014       0.274494  0.397201  0.328305   
22  0.579633  1.959578  2.086774 -0.067658       0.370105  0.285874  0.344021   
23 -0.592464  0.142064 -0.746444  0.241513       0.356540  0.331572  0.311888   
24 -1.000331  0.805433  0.241296 -1.094298       0.317009  0.370879  0.312112   
25  0.800410 -0.292310 -0.207978  0.210215       0.351469  0.289914  0.358616   
26 -0.694713 -0.736950 -2.462557 -0.461109       0.325096  0.363160  0.311744   
27  0.441941 -0.576113 -0.805559  2.352959       0.421190  0.255939  0.322871   
28  0.953125 -0.243615 -0.721178 -0.107908       0.344954  0.294482  0.360564   
29  0.903935  0.024869 -0.142636 -1.382303       0.306249  0.320660  0.373090   
30 -1.662492  0.382524  0.188258  0.673697       0.364516  0.348772  0.286712   
31  0.283288  0.347861  2.155467 -1.161072       0.305787  0.323355  0.370858   
32  1.838184 -1.208997 -0.550096 -0.969791       0.302703  0.287781  0.409516   
33  0.409819  2.893385  2.949921  1.359972       0.431622  0.252158  0.316220   
34  1.173125  0.456231 -0.919657  0.469311       0.378281  0.274208  0.347511   
35  1.139879  0.635218  1.679938 -0.701674       0.329699  0.288940  0.381361   
36 -1.513714 -0.193228 -1.534442  1.096059       0.377432  0.342755  0.279813   
37  0.253740 -0.766162 -0.596398  0.354703       0.347930  0.305869  0.346202   
38  1.624678 -0.745730  0.308826 -1.674172       0.284897  0.303535  0.411568   
39  2.231300 -0.517229 -0.458651  0.535492       0.361962  0.245257  0.392781   
40  0.484733  0.240663 -0.415946 -1.548492       0.304252  0.338488  0.357260   
41  1.373659 -0.978996 -0.300478 -1.986680       0.274433  0.321300  0.404267   
42  0.500844 -0.242093  1.985447  0.423359       0.347400  0.284522  0.368078   
43  0.793489  2.077109  2.719448  1.064257       0.408149  0.252584  0.339267   
44  0.615367 -1.600197  0.590421 -1.374310       0.276490  0.328991  0.394519   
45  0.209659  1.107622 -0.963200 -1.233308       0.329518  0.339931  0.330551   
46  1.395684 -0.079772  2.188615  2.027557       0.404037  0.226759  0.369204   
47 -1.229550 -1.941936 -2.574078  2.513132       0.402689  0.310282  0.287029   
48 -0.464617  2.642717  0.083756 -1.350920